# ROBOT : 'iiwa' 
# TASK  : 3D position target reaching + obstacle avoidance


# General
dt: 0.02                                             # OCP integration step 
N_h: 200                                             # Horizon length in nodes
maxiter: 100                                         # Max number of iterations in DDP
q0: [0.1, 0.7, 0., 0.7, -0.5, 1.5, 0.]               # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                          # Initial robot joint velocity
WHICH_PLOTS: ['ee']                                 # which plots to generate 

# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement' 
#                           'collision'
WHICH_COSTS: ['stateReg', 'velocity', 'translation', 'ctrlRegGrav', 'collision'] 

# Cost terms weights, activations and references
 # 'stateReg' : state regularization  
stateRegWeights: [0., 0., 0., 0., 0., 0. ,0., 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: .1
stateRegWeightTerminal: 2.
stateRegRef: 'DEFAULT' # 'DEFAULT' = [q0, v0]

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.01
ctrlRegRef: 'DEFAULT' # DEFAULT = g(q) | NOT used for 'ctrlRegGrav' cost

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 2.
frameTranslationWeightTerminal: 2. 
frameTranslationRef: [-0.3, -0.3, 0.9]
frameTranslationFrameName: 'contact' # 'DEFAULT' = $(frame_of_interest)

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 0., 0., 0.]
frameVelocityWeight: 0.1
frameVelocityWeightTerminal: 1
frameVelocityRef: [0., 0., 0., 0., 0., 0.]    
frameVelocityFrameName: 'contact' # 'DEFAULT' = $(frame_of_interest)

 # 'collision' : obstacle avoidance cost 
collisionFrameName: 'L7'
collisionCapsuleLength: 0.2
collisionCapsuleRadius: 0.05
collisionCostWeight: 100.
collisionCostWeightTerminal: 100.
collisionObstaclePosition: [-0.2, -0.2, 0.8]
obstacleRadius: 0.03
obstacleLength: 0.5
collisionObstacleSize: 0.03
collisionThreshold: 0.05

 # 'stateLim' : state limits 
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 0.
stateLimWeightTerminal: 0.
coef_xlim: 1.

 # 'ctrlLim' : torque limits ('DEFAULT' = 0)
ctrlLimWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlLimWeight: 0.
coef_ulim: 1.

# armature
armature: [.1, .1, .1, .1, .1, .1, .0]