# ROBOT : 'talos_reduced' 
# TASK  : 3D position target reaching
# with Low-Pass-Filter (LPF) in dynamics


# General 
LPF_TYPE: 1                            # (0) ZOH (1) Euler (2) exact EMA
f_c: 5                                 # Low-pass filter cut-off frequency
tau_plus_integration: False            # semi-implicit if true, explicit if false
dt: 0.02                               # OCP integration step 
N_h: 200                               # Horizon length in nodes
maxiter: 1000                          # Max number of iterations in DDP
q0: [0., 0.006761, -0.25847, -0.173046, 0.0002, -0.525366]    # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.]                                      # Initial robot joint velocity
WHICH_PLOTS: ['all']                                          # which plots to generate 


# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement'
WHICH_COSTS: ['stateReg', 'translation', 'velocity', 'ctrlRegGrav'] 

# Cost terms weights, activations and references
 # 'stateReg' : state regularization  
stateRegWeights: [20, 20,   10,10,10,10,       1,1,  1,1,1,1]
stateRegWeight: 0.1
stateRegWeightTerminal: 0.1
stateRegRef: 'DEFAULT' # 'DEFAULT' = [q0, v0]

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.001
ctrlRegRef: 'DEFAULT' # DEFAULT g(q0) | NOT used for 'ctrlRegGrav' cost


# 'wReg' : unfiltered torque regularization
wRegWeight: 0.001
wRegRef: 'tau0' # in ['zero', 'tau0' , 'gravity']

# 'wLim' : unfiltered torque limit
wLimWeight: 1000.


 # 'translation' : end-effector frame translation 
frameTranslationWeight: 5.
frameTranslationWeightTerminal: 5. 
frameTranslationRef: [0.6, -0.2, 1.]
alpha_quadflatlog: 0.01
frameTranslationFrameName: 'arm_right_7_link' 
 
 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 0., 0., 0.]
frameVelocityWeight: 0.1
frameVelocityWeightTerminal: 1
frameVelocityRef: [0., 0., 0., 0., 0., 0.]    
frameVelocityFrameName: 'arm_right_7_link'  

 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 1000.
stateLimWeightTerminal: 1000.
coef_xlim: 0.9

#  # 'ctrlLim' : torque limits
# ctrlLimWeights: [1., 1., 1., 1., 1., 1.,]
# ctrlLimWeight: 0.
# coef_ulim: 1.

# armature
armature: [0., 0., 0., 0., 0., 0.]