# OCP LPF parameters for end-effector reaching task

# General
dt: 0.01                                             # OCP integration step 
N_h: 200                                             # Horizon length in nodes
maxiter: 100                                         # Max number of iterations in DDP
q0: [0.1, 0.7, 0., 0.7, -0.5, 1.5, 0.]               # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                          # Initial robot joint velocity


# List of contacts
contacts:
  - {
      contactModelFrameName: 'contact',       # frame name in pinocchio model
      pinocchioReferenceFrame: 'LOCAL',       #LOCAL, WORLD, LOCAL_WORLD_ALIGNED
      contactModelType: '1Dz',                # 1Dx, 1Dy, 1Dz, 3D, 6D
      contactModelTranslationRef: '',         # 3d vector
      contactModelRotationRef: '',            # 3d matrix
      contactModelGains: [0, 0.],             # Baumgarte stabilization gains
      active: True                            # Initially active? 
    }

# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement'
WHICH_COSTS: ['force', 'translation', 'stateReg', 'ctrlRegGrav']  

# Cost function weights and activations
 # 'force' : end-effector frame force (translation + rotation)
frameForceWeights:  [0., 0., 1., 0., 0., 0.]
frameForceWeight: 10.
frameForceRef: [0., 0., -20, 0., 0., 0.]    
frameForceFrameName: 'contact'


 # 'stateReg' : state regularization  
stateRegWeights: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: 0.5
stateRegWeightTerminal: 1
stateRegRef: 'DEFAULT'

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.01
ctrlRegRef: 'DEFAULT' # reference not used for 'ctrlRegGrav'

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 1.
frameTranslationWeightTerminal: .1 
frameTranslationRef: 'DEFAULT' 
frameTranslationFrameName: 'contact'

#  # 'velocity' : end-effector frame velocity (translation + rotation)
# frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
# frameVelocityWeight: .1
# frameVelocityWeightTerminal: .1
# frameVelocityRef: 'DEFAULT'    
# frameVelocityFrameName: 'contact'

#  # 'stateLim' : state limits
# stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
# stateLimWeight: 0.
# stateLimWeightTerminal: 0.
# coef_xlim: 1

#  # 'ctrlLim' : torque limits
# ctrlLimWeights: [1., 1., 1., 1., 1., 1., 1.]
# ctrlLimWeight: 0.
# coef_ulim: 1


# armature
armature: [.1, .1, .1, .1, .1, .1, .0]