# ROBOT : 'iiwa' 
# TASK  : normal force task


# General
dt: 0.005                                             # OCP integration step 
N_h: 100                                             # Horizon length in nodes
maxiter: 100                                         # Max number of iterations in DDP
q0: [0.1, 0.7, 0., 0.7, -0.5, 1.5, 0.]               # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                          # Initial robot joint velocity
WHICH_PLOTS: ['all']                                          # which plots to generate 


# Pin model frame name of the end-effector 
#   - Used for frame-related costs and plots generation
#   - Overrides the frame name 'DEFAULT' values below
frame_of_interest: 'contact'

# SOFT CONTACT MODEL
oPc_offset: [0., 0., 0.05]
Kp: 1000
Kv: 30
pinRefFrame: 'LOCAL_WORLD_ALIGNED'
contactType: '3D'

# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement'
WHICH_COSTS: ['force', 'stateReg', 'ctrlReg']  

# Cost function weights and activations
 # 'force' : end-effector frame force (translation + rotation)
# frameForceWeights:  [1., 1., 1., 0., 0., 0.]
frameForceWeight: 0.01
frameForceRef: [0., 0., 10, 0., 0., 0.]    
frameForceFrameName: 'contact'


 # 'stateReg' : state regularization  
stateRegWeights: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: 0.01
stateRegWeightTerminal: 0.01
stateRegRef: 'DEFAULT'

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.0001
ctrlRegRef: [ -0., -31.123713,  -0.77562 ,  -0.782922,   0.,   0.184399,   0.] #'DEFAULT' # reference not used for 'ctrlRegGrav'

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 0.01
frameTranslationWeightTerminal: 0.01
frameTranslationRef: 'DEFAULT'
frameTranslationFrameName: 'contact'

#  # 'velocity' : end-effector frame velocity (translation + rotation)
# frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
# frameVelocityWeight: 10
# frameVelocityWeightTerminal: 10
# frameVelocityRef: 'DEFAULT'    
# frameVelocityFrameName: 'contact'


 # 'rotation' : end-effector frame orientation
frameRotationWeights:  [1., 1., 1.]
frameRotationWeight: 10.
frameRotationWeightTerminal: 10.
frameRotationRef: 'DEFAULT'
frameRotationFrameName: 'contact'


 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 0.
stateLimWeightTerminal: 0.
coef_xlim: 1

 # 'ctrlLim' : torque limits
ctrlLimWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlLimWeight: 0.
coef_ulim: 1


# armature
armature: [.1, .1, .1, .1, .1, .1, .0]