# ROBOT : 'iiwa_reduced' 
# TASK  : normal force task


# General
dt: 0.02                                             # OCP integration step 
N_h: 400                                             # Horizon length in nodes
maxiter: 100                                         # Max number of iterations in DDP
q0: [0.1, 0.7, 0., 0.7]               # Initial robot joint configuration
dq0: [0.,0.,0.,0.]                          # Initial robot joint velocity
WHICH_PLOTS: ['ee', 'f', 'u']                                          # which plots to generate 

# Pin model frame name of the end-effector 
#   - Used for frame-related costs and plots generation
#   - Overrides the frame name 'DEFAULT' values below
frame_of_interest: 'contact'

# List of contacts
contacts:
  - {
      contactModelFrameName: 'contact',               # frame name in pinocchio model
      pinocchioReferenceFrame: 'LOCAL_WORLD_ALIGNED', #LOCAL, WORLD, LOCAL_WORLD_ALIGNED
      contactModelType: '1Dz',                        # 1Dx, 1Dy, 1Dz, 3D, 6D
      contactModelTranslationRef: '',                 # 3d vector
      contactModelRotationRef: '',                    # 3d matrix
      contactModelGains: [2, 5],                     # Baumgarte stabilization gains
      # contactModelGains: [5, 1],                    # Baumgarte stabilization gains
      active: True                                    # Initially active? 
    }

# inv_damping: 100000

# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement'
WHICH_COSTS: ['force', 'translation', 'rotation', 'stateReg', 'ctrlRegGrav']  

# Cost function weights and activations
 # 'force' : end-effector frame force (translation + rotation)
frameForceWeights:  [1., 1., 1., 0., 0., 0.]
frameForceWeight: 10.
frameForceRef: [0., 0., -20, 0., 0., 0.]    
frameForceFrameName: 'contact'

#  # 'friction' : end-effector frame friction cone 
# mu:  0.5
# frictionConeWeight: 1
# frictionConeFrameName: 'contact'

 # 'stateReg' : state regularization  
stateRegWeights: [0.1, 0.1, 0.1, 0.1,  2., 2., 2., 2.]
stateRegWeight: 0.05
stateRegWeightTerminal: 1
stateRegRef: 'DEFAULT'

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1]
ctrlRegWeight: 0.01
ctrlRegRef: 'DEFAULT' # reference not used for 'ctrlRegGrav'

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 0.]
frameTranslationWeight: 100
frameTranslationWeightTerminal: 100
frameTranslationRef: 'DEFAULT'
frameTranslationFrameName: 'contact'

 # 'rotation' : end-effector frame orientation
frameRotationWeights:  [1., 1., 1.]
frameRotationWeight: 10.
frameRotationWeightTerminal: 10.
frameRotationRef: 'DEFAULT'
frameRotationFrameName: 'contact'


 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1.,  1., 1., 1., 1.]
stateLimWeight: 0.
stateLimWeightTerminal: 0.
coef_xlim: 1

 # 'ctrlLim' : torque limits
ctrlLimWeights: [1., 1., 1., 1.]
ctrlLimWeight: 0.
coef_ulim: 1


# armature
armature: [.1, .1, .1, .1]