# ROBOT : 'iiwa' 
# TASK  : normal force task

# MPC & sim parameters
simu_freq: 1000        # Simulation frequency in Hz
ctrl_freq: 100        # Control frequency
plan_freq: 100       # Planning frequency
T_tot: 10            # Simu duration (s)
# Simulation options
DELAY_SIM: False                # Add delay in reference torques (low-level)
DELAY_OCP: False                # Add delay in OCP solution (i.e. ~1ms resolution time)
SCALE_TORQUES: False            # Affine scaling of reference torque
NOISE_TORQUES: False            # Add Gaussian noise on reference torques
FILTER_TORQUES: False           # Moving average smoothing of reference torques
TORQUE_TRACKING: False        # Simulate low-level torque control loop
NOISE_STATE: False              # Add Gaussian noise on the measured state 
FILTER_STATE: False             # Moving average smoothing of reference torques
SAVE_DATA: True                 # Save plot_data to npz
RECORD_SOLVER_DATA: False       # Keep trace of Vxx, Riccati gains, reg, Jacobian etc. (more data to save)
INIT_LOG: True                  # Initial logs summarizing parameters
init_log_display_time: 1        # How long (s) to display the initial logs ?
LOG: True                       # Logs during simulation
log_rate: 500                   # Display sim status once very 'log_rate' sim cycles
WHICH_PLOTS: ['f', 'ee']
RICCATI: False 
FD_ESTIMATE_VELOCITY: True 


# Start of the reaching phase
T_REACH: 1.
# Start of the contact phase
T_CONTACT: 5.


# General
dt: 0.01                                           # OCP integration step 
N_h: 100                                            # Horizon length in nodes
maxiter: 5                                         # Max number of iterations in DDP
# q0: [-0.1194, -0.1913,  0.0971, -1.3812, -0.008 ,  1.885 ,  0.3739]  # Initial robot joint configuration
q0: [0., 0.34, 0., -0.75, 0., 0., 0.]  # Initial robot joint configuration (as in KUKA Java DGM app)
dq0: [0.,0.,0.,0.,0.,0.,0.]            # Initial robot joint velocity


# Pin model frame name of the end-effector 
#   - Used for frame-related costs and plots generation
#   - Overrides the frame name 'DEFAULT' values below
frame_of_interest: 'contact'

# SOFT CONTACT MODEL
oPc_offset: [0., 0., 0.035]
# oPc_offset: [0., 0., -0.035]
Kp: [20000, 20000, 20000] # also works with 10000
Kv: [1600, 1600, 1600] ## also works with 800 (do not underest. real damping)
pinRefFrame: 'LOCAL_WORLD_ALIGNED'
contactType: '3D'
contactPosition: [0.6, 0.0, 0.01]

# #  SOFT CONTACT MODEL
# oPc_offset: [0., 0., 0.035]
# Kp: [20000] # also works with 10000
# Kv: [1600] ## also works with 800 (do not underest. real damping)
# pinRefFrame: 'LOCAL_WORLD_ALIGNED'
# contactType: '1Dz'
# contactPosition: [0.6, 0.0, 0.01]

# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement'
WHICH_COSTS: ['force', 'forceRateReg', 'translation', 'stateReg', 'ctrlRegGrav']  

# Cost function weights and activations
 # 'force' : end-effector frame force (translation + rotation)
# frameForceWeights:  [1., 1., 1., 0., 0., 0.]
frameForceWeight: 10
frameForceRef: [0., 0., 50, 0., 0., 0.]    
frameForceFrameName: 'contact'

forceRateRegWeight: 0.000000001

 # 'stateReg' : state regularization  
stateRegWeights: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: 0.001
stateRegWeightTerminal: 0.001
stateRegRef: 'DEFAULT'

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.00001
ctrlRegRef: 'DEFAULT' 

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 1
frameTranslationWeightTerminal: 10
frameTranslationRef: 'DEFAULT'
frameTranslationFrameName: 'contact'


#  # 'velocity' : end-effector frame velocity (translation + rotation)
# frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
# frameVelocityWeight: 10
# frameVelocityWeightTerminal: 10
# frameVelocityRef: 'DEFAULT'    
# frameVelocityFrameName: 'contact'


 # 'rotation' : end-effector frame orientation
frameRotationWeights:  [1., 1., 1.]
frameRotationWeight: .1
frameRotationWeightTerminal: 0.1
frameRotationRef: 'DEFAULT'
frameRotationFrameName: 'contact'


 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 1000.
stateLimWeightTerminal: 1000.
coef_xlim: 0.95

 # 'ctrlLim' : torque limits
ctrlLimWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlLimWeight: 0.
coef_ulim: 1


# armature
armature:  [.0, .0, .0, .0, .0, .0, .0]

# # # # # # # # # # # # # # # # # # # # # #
# Low-level simulation (actuation model)  #
# # # # # # # # # # # # # # # # # # # # # #
  # Scaling of desired torque
alpha_min: 0.95
alpha_max: 1.05
beta_min: -0.1
beta_max: 0.1
  # White noise on desired torque and measured state
var_u: [1.5, 1.5, 1.0, 1.0, 0.5, 0.5, 0.5]
var_q: 0.028 #x10
var_v: 0.028 #x10
var_aug: [3.0, 3.0, 3.0] # Force 
  # Buffer for torque delay
delay_OCP_ms: 1    # in ms
delay_sim_cycle: 2 # in HF cycles
  # Proportional-integral torque control gains
Kp_low: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
Ki_low: [.001, .001, .001, .001, .001, .001, .01]
Kd_low: [.0, .0, .0, .0, .0, .0, .0]
u_avg_filter_length: 5 #8 # in HF cycles
x_avg_filter_length: 20  #20 #8 # in HF cycles