# ROBOT : 'iiwa' 
# TASK  : normal force task with constraints


# General
dt: 0.02                                             # OCP integration step 
N_h: 50                                              # Horizon length in nodes
maxiter: 100                                         # Max number of iterations in DDP
q0: [0.1, 0.7, 0., 0.7, -0.5, 1.5, 0.]               # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                          # Initial robot joint velocity
# WHICH_PLOTS: ['ee', 'f', 'u']                        # which plots to generate 
WHICH_PLOTS: ['f']                        # which plots to generate 


# List of contacts
contacts:
  - {
      contactModelFrameName: 'contact',               # frame name in pinocchio model
      pinocchioReferenceFrame: 'LOCAL_WORLD_ALIGNED',               # LOCAL, WORLD, LOCAL_WORLD_ALIGNED
      contactModelType: '6D',                         # 1Dx, 1Dy, 1Dz, 3D, 6D
      contactModelTranslationRef: '',                 # 3d vector
      contactModelRotationRef: '',                    # 3d matrix
      contactModelGains: [0, 50],                     # Baumgarte stabilization gains
      active: True                                    # Initially active? 
    }

# Constraints 
WHICH_CONSTRAINTS: ['forceBox']
forceConstraintType: '6D'
forceLowerLimit: [-10000, -10000, 0, -10000, -10000, -10000]
forceUpperLimit: [10000, 10000, 40, 10000, 10000, 10000]
forceConstraintFrameName: 'contact'
forceConstraintReferenceFrame: 'LOCAL_WORLD_ALIGNED'

# FADMM solver parameters
USE_PROXQP: False
maxiter: 10                                        # Max number of iterations in DDP
with_callbacks: True
use_filter_ls: True
filter_size: 10
termination_tol: 0.0000001
warm_start: True
max_qp_iters: 1000    #125 
qp_termination_tol_abs: 0.00001
qp_termination_tol_rel: 0.00001

warm_start_y: False 
reset_rho: False

# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement'
WHICH_COSTS: ['force', 'translation', 'stateReg', 'ctrlRegGrav']  

# Cost function weights and activations
 # 'force' : end-effector frame force (translation + rotation)
frameForceWeights:  [1., 1., 1., 1., 1., 1.]
frameForceWeight: 10.
frameForceRef: [0., 0., 50, 0., 0., 0.]    
frameForceFrameName: 'contact'

#  # 'friction' : end-effector frame friction cone 
# mu:  0.5
# frictionConeWeight: 1
# frictionConeFrameName: 'contact'

 # 'stateReg' : state regularization  
stateRegWeights: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: 0.05
stateRegWeightTerminal: 1
stateRegRef: 'DEFAULT'

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.01
ctrlRegRef: 'DEFAULT' # reference not used for 'ctrlRegGrav'

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 0.]
frameTranslationWeight: 100
frameTranslationWeightTerminal: 100
frameTranslationRef: 'DEFAULT'
frameTranslationFrameName: 'contact'


# armature
armature: [0., 0., 0., 0., 0., 0., .0]