# ROBOT : 'talos_reduced' 
# TASK  : normal force task

# with Low-Pass-Filter (LPF) in dynamics


# MPC & sim parameters
simu_freq: 1000        # Simulation frequency in Hz
ctrl_freq: 250        # Control frequency
plan_freq: 250        # Planning frequency
T_tot: 2.             # Simu duration (s)
# Simulation options
DELAY_SIM: False                # Add delay in reference torques (low-level)
DELAY_OCP: False                # Add delay in OCP solution (i.e. ~1ms resolution time)
SCALE_TORQUES: False            # Affine scaling of reference torque
NOISE_TORQUES: False            # Add Gaussian noise on reference torques
FILTER_TORQUES: False           # Moving average smoothing of reference torques
TORQUE_TRACKING: False          # Simulate low-level torque control loop
NOISE_STATE: False              # Add Gaussian noise on the measured state 
FILTER_STATE: False             # Moving average smoothing of reference torques
SAVE_DATA: False                 # Save plot_data to npz
RECORD_SOLVER_DATA: False       # Keep trace of Vxx, Riccati gains, reg, Jacobian etc. (more data to save)
INIT_LOG: True                  # Initial logs summarizing parameters
init_log_display_time: 1        # How long (s) to display the initial logs ?
LOG: True                       # Logs during simulation
log_rate: 500                   # Display sim status once very 'log_rate' sim cycles
WHICH_PLOTS: ['all']
RICCATI: True


# Definition of the contact surface in the simulator
# It is aligned with the LOCAL contact frame by default
# User-defined offset expressed in the LOCAL contact frame :
contact_plane_offset: [0., 0., -0.245 ]


# General 
LPF_TYPE: 1                            # (0) ZOH (1) Euler (2) exact EMA
f_c: 5                                 # Low-pass filter cut-off frequency
tau_plus_integration: False            # semi-implicit if true, explicit if false
dt: 0.01                                                      # OCP integration step 
N_h: 100                                                      # Horizon length in nodes
maxiter: 5                                                  # Max number of iterations in DDP
q0: [0., 0.006761, -0.25847, -0.25, 0.0002, -0.525366]    # Initial robot joint configuration
# q0: [0., 0.006761, -0.25847, -0.173046, 0.0002, -0.525366]    # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.]                                      # Initial robot joint velocity


# Pin model frame name of the end-effector 
#   - Used for frame-related costs and plots generation
#   - Overrides the frame name 'DEFAULT' values below
frame_of_interest: 'arm_right_7_link'

# List of contacts
contacts:
  - {
      contactModelFrameName: 'arm_right_7_link',       # frame name in pinocchio model
      pinocchioReferenceFrame: 'LOCAL_WORLD_ALIGNED',       #LOCAL, WORLD, LOCAL_WORLD_ALIGNED
      contactModelType: '3D',                 # 1Dx, 1Dy, 1Dz, 3D, 6D
      contactModelTranslationRef: '',         # 3d vector
      contactModelRotationRef: '',            # 3d matrix
      contactModelGains: [0, 50.],             # Baumgarte stabilization gains
      active: True                            # Initially active? 
    }


# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement'
WHICH_COSTS: ['force', 'stateReg', 'ctrlReg'] 

# Cost function weights and activations
 # 'force' : end-effector frame force (translation + rotation)
frameForceWeights:  [1., 1., 1., 0., 0., 0.]
frameForceWeight: 20.
frameForceRef: [0., 0., -50, 0., 0., 0.]    
frameForceFrameName: 'arm_right_7_link'

# 'wReg' : unfiltered torque regularization
wRegWeight: 0.005
wRegRef: 'tau0' # in ['zero', 'tau0' , 'gravity']

# 'wLim' : unfiltered torque limit
wLimWeight: 100


 # 'stateReg' : state regularization  
stateRegWeights: [20, 20,   10,10,10,10,       1,1,  1,1,1,1]
stateRegWeight: 0.1
stateRegWeightTerminal: 0.1
stateRegRef: 'DEFAULT' # 'DEFAULT' = [q0, v0]

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.001
ctrlRegWeightTerminal: 0.001
ctrlRegRef: 'DEFAULT' # DEFAULT g(q0) | NOT used for 'ctrlRegGrav' cost

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 0.]
frameTranslationWeight: 100
frameTranslationWeightTerminal: 100
frameTranslationRef: 'DEFAULT'
frameTranslationFrameName: 'arm_right_7_link' 
 
 # 'rotation' : end-effector frame orientation
frameRotationWeights:  [1., 1., 1.]
frameRotationWeight: 10.
frameRotationWeightTerminal: 10.
frameRotationRef: 'DEFAULT'
frameRotationFrameName: 'arm_right_7_link'

 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 1000.
stateLimWeightTerminal: 1000.
coef_xlim: 0.9

#  # 'ctrlLim' : torque limits
# ctrlLimWeights: [1., 1., 1., 1., 1., 1.,]
# ctrlLimWeight: 0.
# coef_ulim: 1.

# armature
armature: [0., 0., 0., 0., 0., 0.]


# # # # # # # # # # # # # # # # # # # # # #
# Low-level simulation (actuation model)  #
# # # # # # # # # # # # # # # # # # # # # #
  # Scaling of desired torque
alpha_min: 0.95
alpha_max: 1.05
beta_min: -0.1
beta_max: 0.1
  # White noise on desired torque and measured state
var_u: [3.0, 3.0, 2.0, 2.0, 1.0, 0.1]
var_q: 0.028 #x10
var_v: 0.028 #x10
  # Buffer for torque delay
delay_OCP_ms: 1    # in ms
delay_sim_cycle: 2 # in HF cycles
  # Proportional-integral torque control gains
Kp_low: [.2, .2, .2, .2, .2, .2]
Ki_low: [.001, .001, .001, .001, .001, .001]
Kd_low: [.00001, .00001, .00001, .00001, .00001, .00001]
u_avg_filter_length: 20 #8 # in HF cycles
x_avg_filter_length: 5  #20 #8 # in HF cycles