# ROBOT : 'talos_reduced' 
# TASK  : normal force task


# General
dt: 0.02                                                      # OCP integration step 
N_h: 100                                                      # Horizon length in nodes
maxiter: 100                                                  # Max number of iterations in DDP
q0: [0., 0.006761, -0.25847, -0.173046, 0.0002, -0.525366]    # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.]                                      # Initial robot joint velocity
WHICH_PLOTS: ['f']                                          # which plots to generate 


# Pin model frame name of the end-effector 
#   - Used for frame-related costs and plots generation
#   - Overrides the frame name 'DEFAULT' values below
frame_of_interest: 'arm_right_7_link'


# List of contacts
contacts:
  - {
      contactModelFrameName: 'arm_right_7_link',       # frame name in pinocchio model
      pinocchioReferenceFrame: 'LOCAL_WORLD_ALIGNED',       #LOCAL, WORLD, LOCAL_WORLD_ALIGNED
      contactModelType: '1Dz',                 # 1Dx, 1Dy, 1Dz, 3D, 6D
      contactModelTranslationRef: '',         # 3d vector
      contactModelRotationRef: '',            # 3d matrix
      contactModelGains: [5, 10.],             # Baumgarte stabilization gains
      active: True                            # Initially active? 
    }


# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement'
WHICH_COSTS: ['force', 'stateReg', 'translation', 'ctrlRegGrav'] 

# Cost function weights and activations
 # 'force' : end-effector frame force (translation + rotation)
frameForceWeights:  [0., 0., 1., 0., 0., 0.]
frameForceWeight: 10.
frameForceRef: [0., 0., -20, 0., 0., 0.]    
frameForceFrameName: 'arm_right_7_link'


 # 'stateReg' : state regularization  
stateRegWeights: [20, 20,   10,10,10,10,       1,1,  1,1,1,1]
stateRegWeight: 0.01
stateRegWeightTerminal: 1.
stateRegRef: 'DEFAULT' # 'DEFAULT' = [q0, v0]

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.0001
ctrlRegRef: 'DEFAULT' # DEFAULT g(q0) | NOT used for 'ctrlRegGrav' cost

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 0.]
frameTranslationWeight: 1
frameTranslationWeightTerminal: 1
frameTranslationRef: 'DEFAULT'
frameTranslationFrameName: 'arm_right_7_link' 
 
 # 'rotation' : end-effector frame orientation
frameRotationWeights:  [1., 1., 1.]
frameRotationWeight: 10.
frameRotationWeightTerminal: 10.
frameRotationRef: 'DEFAULT'
frameRotationFrameName: 'arm_right_7_link'

 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 1000.
stateLimWeightTerminal: 1000.
coef_xlim: 0.9

#  # 'ctrlLim' : torque limits
# ctrlLimWeights: [1., 1., 1., 1., 1., 1.,]
# ctrlLimWeight: 0.
# coef_ulim: 1.

# armature
armature: [0., 0., 0., 0., 0., 0.]