# OCP LPF parameters for end-effector circle force task

# # Goal placement M = ( M_ee.rot @ rpyToMat(0, pi/2, 0) , [0.3, 0., 0.7] )
#   R =
#    -0.918754     0.389418    0.0651533
#     0.388443     0.921061   -0.0275464
#   -0.0707372 -2.41653e-08    -0.997495
#   p = 0.3   0 0.7
# # Starting config for IK (to avoid self-collision solution)
# q_init =  [-0.2263,  0.    , -0.174 , -1.6865,  0.0358,  1.5   , -0.3946]
# # Solution of IK_placement(q_init, M)
# q0 = [-0.1194, -0.1913,  0.0971, -1.3812, -0.008 ,  1.885 ,  0.3739]


# General 
LPF_TYPE: 1
f_c: 2                                                               # Low-pass filter cut-off frequency
tau_plus_integration: False
dt: 0.02                                                            # OCP integration step 
N_h: 400                                                             # Horizon length in nodes
maxiter: 100                                                         # Max number of iterations in DDP
q0: [-0.1194, -0.1913,  0.0971, -1.3812, -0.008 ,  1.885 ,  0.3739]  # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                                          # Initial robot joint velocity
tau0: [  0., -16.4279,  -0.,  14.4554, -0.6963, 0.027, 0.]           # Initial robot joint torque
WHICH_PLOTS: ['all']

# Pin model frame name of the end-effector 
#   - Used for frame-related costs and plots generation
#   - Overrides the frame name 'DEFAULT' values below
frame_of_interest: 'contact'

# List of contacts
contacts:
  - {
      contactModelFrameName: 'contact',       # frame name in pinocchio model
      pinocchioReferenceFrame: 'LOCAL_WORLD_ALIGNED',       #LOCAL, WORLD, LOCAL_WORLD_ALIGNED
      contactModelType: '1Dz',                # 1Dx, 1Dy, 1Dz, 3D, 6D
      contactModelTranslationRef: '',         # 3d vector
      contactModelRotationRef: '',            # 3d matrix
      contactModelGains: [0, 0.],             # Baumgarte stabilization gains
      active: True                            # Initially active? 
    }
  # - {
  #     contactModelFrameName: 'A1',
  #     pinocchioReferenceFrame: 'LOCAL',
  #     contactModelType: '3D',
  #     contactModelTranslationRef: '',
  #     contactModelRotationRef: '',
  #     contactModelGains: [0., 10.],
  #     active: False
  #   }


# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement', 'rotation'
WHICH_COSTS: ['force', 'translation', 'rotation', 'stateReg',  'stateLim']  

# Cost function weights and activations
 # 'force' : end-effector frame force (translation + rotation)
frameForceWeights:  [0., 0., 1., 0., 0., 0.]
frameForceWeight: 10
# frameForceWeightTerminal: 0.
frameForceRef: [0., 0., -20, 0., 0., 0.]    
frameForceFrameName: 'contact'

 # 'friction' : end-effector frame friction cone 
mu:  0.5
frictionConeWeight: 1
frictionConeFrameName: 'contact'

# Cost function weights and activations
 # 'stateReg' : state regularization  
stateRegWeights: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1 ,0.1, 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: 0.1
stateRegWeightTerminal: 1.
stateRegRef: 'DEFAULT' # TRACKING ?

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.01
ctrlRegWeightTerminal: 10 
ctrlRegRef: 'DEFAULT'  # reference not used for 'ctrlRegGrav'


# 'wReg' : unfiltered torque regularization
wRegWeight: 0.001
wRegRef: 'tau0' # in ['zero', 'tau0' , 'gravity']

# 'wLim' : unfiltered torque limit
wLimWeight: 100.


 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 20.
frameTranslationWeightTerminal: 20.
frameTranslationRef: 'DEFAULT' 
frameTranslationFrameName: 'contact'
frameCircleTrajectoryRadius: 0.1  # in m
frameCircleTrajectoryVelocity: 1.5 # in rad/s
numberOfRounds: 1
# CIRCLE_LOCAL_PLANE: 'YZ'             # LOCAL plane in which the circle lies # x-force
# CIRCLE_LOCAL_PLANE: 'XZ'             # LOCAL plane in which the circle lies # y-force
CIRCLE_LOCAL_PLANE: 'XY'

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
frameVelocityWeight: 0.
frameVelocityWeightTerminal: 100
frameVelocityRef: 'DEFAULT'    
frameVelocityFrameName: 'contact'


 # 'rotation' : end-effector frame orientation
frameRotationWeights:  [1., 1., 1.]
frameRotationWeight: 1.
frameRotationWeightTerminal: 1.
frameRotationRef: 'DEFAULT'
frameRotationFrameName: 'contact'


 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 100.
stateLimWeightTerminal: 100.
coef_xlim: 1

 # 'ctrlLim' : torque limits
ctrlLimWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlLimWeight: 100.
ctrlLimWeightTerminal: 100.
coef_ulim: 1

# armature
armature: [.1, .1, .1, .1, .1, .1, .0]