# OCP parameters for end-effector circle force task 

# # Goal placement M = ( M_ee.rot @ rpyToMat(0, pi/2, 0) , [0.3, 0., 0.7] )
#   R =
#    -0.918754     0.389418    0.0651533
#     0.388443     0.921061   -0.0275464
#   -0.0707372 -2.41653e-08    -0.997495
#   p = 0.3   0 0.7
# # Starting config for IK (to avoid self-collision solution)
# q_init =  [-0.2263,  0.    , -0.174 , -1.6865,  0.0358,  1.5   , -0.3946]
# # Solution of IK_placement(q_init, M)
# q0 = [-0.1194, -0.1913,  0.0971, -1.3812, -0.008 ,  1.885 ,  0.3739]


# General
dt: 0.02                                                             # OCP integration step 
N_h: 400                                                             # Horizon length in nodes
maxiter: 100                                                         # Max number of iterations in DDP
q0: [-0.1194, -0.1913,  0.0971, -1.3812, -0.008 ,  1.885 ,  0.3739]  # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                                          # Initial robot joint velocity
WHICH_PLOTS: ['all']


# List of contacts
contacts:
  - {
      contactModelFrameName: 'contact',       # frame name in pinocchio model
      pinocchioReferenceFrame: 'LOCAL_WORLD_ALIGNED',       #LOCAL, WORLD, LOCAL_WORLD_ALIGNED
      contactModelType: '1Dz',                # 1Dx, 1Dy, 1Dz, 3D, 6D
      contactModelTranslationRef: '',         # 3d vector
      contactModelRotationRef: '',            # 3d matrix
      contactModelGains: [10, 50.],             # Baumgarte stabilization gains
      active: True                            # Initially active? 
    }
  # - {
  #     contactModelFrameName: 'A1',
  #     pinocchioReferenceFrame: 'LOCAL',
  #     contactModelType: '3D',
  #     contactModelTranslationRef: '',
  #     contactModelRotationRef: '',
  #     contactModelGains: [0., 10.],
  #     active: False
  #   }

# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement', 'rotation'
WHICH_COSTS: ['force', 'translation', 'rotation', 'stateReg', 'ctrlRegGrav']  

# Cost function weights and activations
 # 'force' : end-effector frame force (translation + rotation)
frameForceWeights:  [1., 1., 1., 1., 1., 1.] # z-force 
frameForceWeight: 10
frameForceRef: [0., 0., -20, 0., 0., 0.]     # z-force 
frameForceFrameName: 'contact'


 # 'stateReg' : state regularization  
stateRegWeights: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: 0.01
stateRegWeightTerminal: 1.
stateRegRef: 'DEFAULT' # TRACKING ?

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegGravWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegGravWeight: 0.0001
ctrlRegRef: 'DEFAULT'  # reference not used for 'ctrlRegGrav'

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 0.] # z-force 
frameTranslationWeight: 10
frameTranslationWeightTerminal: 10.
frameTranslationRef: 'DEFAULT' 
frameTranslationFrameName: 'contact'
frameCircleTrajectoryRadius: 0.1  # in m
frameCircleTrajectoryVelocity: 1.5 # in rad/s
# CIRCLE_LOCAL_PLANE: 'YZ'             # LOCAL plane in which the circle lies # x-force
# CIRCLE_LOCAL_PLANE: 'XZ'             # LOCAL plane in which the circle lies # y-force
CIRCLE_LOCAL_PLANE: 'XY'             # LOCAL plane in which the circle lies # z-force

 # 'rotation' : end-effector frame orientation
frameRotationWeights:  [1., 1., 1.]
frameRotationWeight: 10.
frameRotationWeightTerminal: 10.
frameRotationRef: 'DEFAULT'
frameRotationFrameName: 'contact'

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
frameVelocityWeight: .1
frameVelocityWeightTerminal: .1
frameVelocityRef: 'DEFAULT'    
frameVelocityFrameName: 'contact'

 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 0.
stateLimWeightTerminal: 0.
coef_xlim: 1

 # 'ctrlLim' : torque limits
ctrlLimWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlLimWeight: 0.
coef_ulim: 1

# armature
armature: [.1, .1, .1, .1, .1, .1, .0]
