# MPC parameters for EE reaching task LPF
# + PyBullet or Raisim simulation


# MPC & sim parameters
simu_freq: 1000        # Simulation frequency in Hz
ctrl_freq: 250       # Control frequency
plan_freq: 250          # Planning frequency
T_tot: 5.             # Simu duration (s)
# Simulation options
DELAY_SIM: True              # Add delay in reference torques (low-level)
DELAY_OCP: True              # Add delay in OCP solution (i.e. ~1ms resolution time)
SCALE_TORQUES: True          # Affine scaling of reference torque
NOISE_TORQUES: True          # Add Gaussian noise on reference torques
FILTER_TORQUES: False         # Moving average smoothing of reference torques
NOISE_STATE: True            # Add Gaussian noise on the measured state 
FILTER_STATE: False           # Moving average smoothing of reference torques
SAVE_DATA: False               # Save plot_data to npz
RECORD_SOLVER_DATA: False     # Keep trace of Vxx, Riccati gains, reg, Jacobian etc. (more data to save)
INIT_LOG: True                # Initial logs summarizing parameters
init_log_display_time: 1      # How long (s) to display the initial logs ?
LOG: True                     # Logs during simulation
log_rate: 500                 # Display sim status once very 'log_rate' sim cycles
WHICH_PLOTS: ['all']
TILT_SURFACE: False           # Tilt contact surface 
TILT_PITCH_LOCAL_DEG: -10.

# # Goal placement M = ( M_ee.rot @ rpyToMat(0, pi/2, 0) , [0.3, 0., 0.7] )
#   R =
#    -0.918754     0.389418    0.0651533
#     0.388443     0.921061   -0.0275464
#   -0.0707372 -2.41653e-08    -0.997495
#   p = 0.3   0 0.7
# # Starting config for IK (to avoid self-collision solution)
# q_init =  [-0.2263,  0.    , -0.174 , -1.6865,  0.0358,  1.5   , -0.3946]
# # Solution of IK_placement(q_init, M)
# q0 = [-0.1194, -0.1913,  0.0971, -1.3812, -0.008 ,  1.885 ,  0.3739]


# General 
LPF_TYPE: 1
f_c: 5                                                               # Low-pass filter cut-off frequency
tau_plus_integration: False
dt: 0.01                                                             # OCP integration step 
N_h: 100                                                             # Horizon length in nodes
maxiter: 5                                                        # Max number of iterations in DDP
q0: [-0.1194, -0.1913,  0.0971, -1.3812, -0.008 ,  1.885 ,  0.3739]  # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                                          # Initial robot joint velocity
tau0: [  0., -16.4279,  -0.,  14.4554, -0.6963, 0.027, 0.]           # Initial robot joint torque

# Contact model 
frame_of_interest: 'arm_right_7_link'
CONTACT: 'True'                         # 'True' or 'False' 
contactModelType: '1D'                  # select in ['1D', '3D', '6D'] (cf. Crocoddyl contact models)
contactModelFrameName: 'arm_right_7_link'
contactModelTranslationRef: 'DEFAULT'   # Position of contact frame in WORLD frame 
contactModelRotationRef: 'DEFAULT'      # Orientation of contact frame in WORLD frame (! for '6D' contact only !)
contactModelGains: [0., 0.]             # Baumgarte stabilization gains 
# 1. 10
# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement', 'rotation'
WHICH_COSTS: ['force', 'translation', 'rotation', 'stateReg', 'stateLim'] # 'ctrlRegGrav']  

# Cost function weights and activations
 # 'force' : end-effector frame force (translation + rotation)
frameForceWeights:  [0., 0., 1., 0., 0., 0.]
frameForceWeight: 10.
# frameForceWeightTerminal: 0.
frameForceRef: [0., 0., -20, 0., 0., 0.]    
frameForceFrameName: 'arm_right_7_link'

 # 'friction' : end-effector frame friction cone 
mu:  0.5
frictionConeWeight: 1
frictionConeFrameName: 'arm_right_7_link'

# Cost function weights and activations
 # 'stateReg' : state regularization  
stateRegWeights: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1 ,0.1, 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: 0.001
stateRegWeightTerminal: 0.001
stateRegRef: 'DEFAULT' # TRACKING ?

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.01
ctrlRegWeightTerminal: 0.01 
ctrlRegRef: 'DEFAULT'  # reference not used for 'ctrlRegGrav'

# 'wReg' : unfiltered torque regularization
wRegWeight: 0.0001

# 'wLim' : unfiltered torque limit
wLimWeight: 100

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 30.
frameTranslationWeightTerminal: 30.
frameTranslationRef: 'DEFAULT' 
frameTranslationFrameName: 'arm_right_7_link'
frameCircleTrajectoryRadius: 0.1  # in m
frameCircleTrajectoryVelocity: 1.5 # in rad/s

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
frameVelocityWeight: 0.
frameVelocityWeightTerminal: 100
frameVelocityRef: 'DEFAULT'    
frameVelocityFrameName: 'arm_right_7_link'


 # 'rotation' : end-effector frame orientation
frameRotationWeights:  [1., 1., 1.]
frameRotationWeight: 1.
frameRotationWeightTerminal: 1.
frameRotationRef: 'DEFAULT'
frameRotationFrameName: 'arm_right_7_link'


 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 100.
stateLimWeightTerminal: 100.
stateLimRef: 'DEFAULT'

 # 'ctrlLim' : torque limits
ctrlBounds: [320, 320, 176, 176, 110, 40, 40]
ctrlLimWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlLimWeight: 100.
ctrlLimWeightTerminal: 100.
ctrlLimRef: 'DEFAULT'

# armature
armature: [.1, .1, .1, .1, .1, .1, .0]


# # # # # # # # # # # # # # # # # # # # # #
# Low-level simulation (actuation model)  #
# # # # # # # # # # # # # # # # # # # # # #
  # Scaling of desired torque
alpha_min: 0.95
alpha_max: 1.05
beta_min: -0.1
beta_max: 0.1
  # White noise on desired torque and measured state
var_u: [3.0, 3.0, 2.0, 2.0, 1.0, 0.1, 0.1]
var_q: 0.028 #x10
var_v: 0.028 #x10
  # Buffer for torque delay
delay_OCP_ms: 1    # in ms
delay_sim_cycle: 1 # in HF cycles
  # Proportional-integral torque control gains
Kp: [.2, .2, .2, .2, .2, .2, .2  ]
Ki: [.001, .001, .001, .001, .001, .001, .01]
Kd: [.00001, .00001, .00001, .00001, .00001, .00001, .00001]
u_avg_filter_length: 20 #8 # in HF cycles
x_avg_filter_length: 5  #20 #8 # in HF cycles