/*
 * This file has been automatically generated by the jrl-cmakemodules.
 * Please see https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/config.hh.cmake for details.
*/

#ifndef FORCE_FEEDBACK_MPC_CONFIG_HH
# define FORCE_FEEDBACK_MPC_CONFIG_HH

// Package version (header).
# define FORCE_FEEDBACK_MPC_VERSION_UNKNOWN_TAG 0 // Used to mention that the current version is unknown.
# define FORCE_FEEDBACK_MPC_VERSION "1.0"
# define FORCE_FEEDBACK_MPC_MAJOR_VERSION 1
# define FORCE_FEEDBACK_MPC_MINOR_VERSION 0
# define FORCE_FEEDBACK_MPC_PATCH_VERSION 

#define FORCE_FEEDBACK_MPC_VERSION_AT_LEAST(major, minor, patch) (FORCE_FEEDBACK_MPC_MAJOR_VERSION>major || (FORCE_FEEDBACK_MPC_MAJOR_VERSION>=major && \
                                                             (FORCE_FEEDBACK_MPC_MINOR_VERSION>minor || (FORCE_FEEDBACK_MPC_MINOR_VERSION>=minor && \
                                                                                                     FORCE_FEEDBACK_MPC_PATCH_VERSION>=patch))))

#define FORCE_FEEDBACK_MPC_VERSION_AT_MOST(major, minor, patch) (FORCE_FEEDBACK_MPC_MAJOR_VERSION<major || (FORCE_FEEDBACK_MPC_MAJOR_VERSION<=major && \
                                                            (FORCE_FEEDBACK_MPC_MINOR_VERSION<minor || (FORCE_FEEDBACK_MPC_MINOR_VERSION<=minor && \
                                                                                                     FORCE_FEEDBACK_MPC_PATCH_VERSION<=patch))))

// Handle portable symbol export.
// Defining manually which symbol should be exported is required
// under Windows whether MinGW or MSVC is used.
//
// The headers then have to be able to work in two different modes:
// - dllexport when one is building the library,
// - dllimport for clients using the library.
//
// On Linux, set the visibility accordingly. If C++ symbol visibility
// is handled by the compiler, see: http://gcc.gnu.org/wiki/Visibility
# if defined _WIN32 || defined __CYGWIN__
// On Microsoft Windows, use dllimport and dllexport to tag symbols.
#  define FORCE_FEEDBACK_MPC_DLLIMPORT __declspec(dllimport)
#  define FORCE_FEEDBACK_MPC_DLLEXPORT __declspec(dllexport)
#  define FORCE_FEEDBACK_MPC_DLLLOCAL
# else
// On Linux, for GCC >= 4, tag symbols using GCC extension.
#  if __GNUC__ >= 4
#   define FORCE_FEEDBACK_MPC_DLLIMPORT __attribute__ ((visibility("default")))
#   define FORCE_FEEDBACK_MPC_DLLEXPORT __attribute__ ((visibility("default")))
#   define FORCE_FEEDBACK_MPC_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
// Otherwise (GCC < 4 or another compiler is used), export everything.
#   define FORCE_FEEDBACK_MPC_DLLIMPORT
#   define FORCE_FEEDBACK_MPC_DLLEXPORT
#   define FORCE_FEEDBACK_MPC_DLLLOCAL
#  endif // __GNUC__ >= 4
# endif // defined _WIN32 || defined __CYGWIN__

# ifdef FORCE_FEEDBACK_MPC_STATIC
// If one is using the library statically, get rid of
// extra information.
#  define FORCE_FEEDBACK_MPC_DLLAPI
#  define FORCE_FEEDBACK_MPC_LOCAL
# else
// Depending on whether one is building or using the
// library define DLLAPI to import or export.
#  ifdef force_feedback_mpc_EXPORTS
#   define FORCE_FEEDBACK_MPC_DLLAPI FORCE_FEEDBACK_MPC_DLLEXPORT
#  else
#   define FORCE_FEEDBACK_MPC_DLLAPI FORCE_FEEDBACK_MPC_DLLIMPORT
#  endif // FORCE_FEEDBACK_MPC_EXPORTS
#  define FORCE_FEEDBACK_MPC_LOCAL FORCE_FEEDBACK_MPC_DLLLOCAL
# endif // FORCE_FEEDBACK_MPC_STATIC
#endif //! FORCE_FEEDBACK_MPC_CONFIG_HH
