# ROBOT : 'talos_arm' 
# TASK  : circle trajectory tracking
# with Low-Pass-Filter (LPF) in dynamics


# MPC & sim parameters
simu_freq: 1000        # Simulation frequency in Hz
ctrl_freq: 250         # Control frequency
plan_freq: 250         # Planning frequency
T_tot: 3.                # Simu duration (s)
# Simulation options
DELAY_SIM: False              # Add delay in reference torques (low-level)
DELAY_OCP: False              # Add delay in OCP solution (i.e. ~1ms resolution time)
SCALE_TORQUES: False          # Affine scaling of reference torque
NOISE_TORQUES: False          # Add Gaussian noise on reference torques
TORQUE_TRACKING: False        # Simulate low-level torque control loop
FILTER_TORQUES: False         # Moving average smoothing of reference torques
NOISE_STATE: False            # Add Gaussian noise on the measured state 
FILTER_STATE: False           # Moving average smoothing of reference torques
SAVE_DATA: False               # Save plot_data to npz
RECORD_SOLVER_DATA: False     # Keep trace of Vxx, Riccati gains, reg, Jacobian etc. (more data to save)
INIT_LOG: True                # Initial logs summarizing parameters
init_log_display_time: 1      # How long (s) to display the initial logs ?
LOG: True                     # Logs during simulation
log_rate: 500                 # Display sim status once very 'log_rate' sim cycles
WHICH_PLOTS: ['all']


# General 
LPF_TYPE: 1
f_c: 5                                 # Low-pass filter cut-off frequency
tau_plus_integration: False
dt: 0.02                               # OCP integration step 
N_h: 100                               # Horizon length in nodes
maxiter: 5                          # Max number of iterations in DDP
q0: [ 2.,  1.5    , -1.1781,  0.    ,  0.    ,  0.    , -0.5236]
dq0: [0.,0.,0.,0.,0.,0.,0.]            # Initial robot joint velocity



# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'translation', 'velocity',
WHICH_COSTS: ['translation', 'stateReg', 'stateLim']  

# Cost function weights and activations
 # 'stateReg' : state regularization  
stateRegWeights: [0., 0., 0., 0., 0., 0. ,0., 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: 0.01
stateRegWeightTerminal: 0.01
stateRegRef: 'DEFAULT'  # 'DEFAULT' = [q0, v0]

 # 'ctrlReg' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.01
ctrlRegWeightTerminal: 0.01
ctrlRegRef: 'DEFAULT'  # DEFAULT = g(q) | NOT used for 'ctrlRegGrav' cost

# 'wReg' : unfiltered torque regularization
wRegWeight: 0.001
wRegRef: 'tau0'  # in ['zero', 'tau0', 'gravity']

# 'wLim' : unfiltered torque limit
wLimWeight: 10.


 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 50.
frameTranslationWeightTerminal: 50.
frameTranslationRef: 'DEFAULT' 
frameTranslationFrameName: 'gripper_left_joint'  
frameCircleTrajectoryRadius: 0.1       # in m
frameCircleTrajectoryVelocity: 1.5     # in rad/s
CIRCLE_LOCAL_PLANE: 'XZ'               # LOCAL plane in which the circle lies

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
frameVelocityWeight: .1
frameVelocityWeightTerminal: .1
frameVelocityRef: 'DEFAULT'      
frameVelocityFrameName: 'gripper_left_joint'

 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 100.
stateLimWeightTerminal: 100.
coef_xlim: 1.

 # 'ctrlLim' : torque limits
# ctrlLimWeights: [1., 1., 1., 1., 1., 1., 1.]
# ctrlLimWeight: 0.
# ctrlLimWeightTerminal: 0.
# coef_ulim: 1.

# armature
armature: [.1, .1, .1, .1, .1, .1, .0]



# # # # # # # # # # # # # # # # # # # # # #
# Low-level simulation (actuation model)  #
# # # # # # # # # # # # # # # # # # # # # #
  # Scaling of desired torque
alpha_min: 0.95
alpha_max: 1.05
beta_min: -0.1
beta_max: 0.1
  # White noise on desired torque and measured state
var_u: [3.0, 3.0, 2.0, 2.0, 1.0, 0.1, 0.1]
var_q: 0.028 #x10
var_v: 0.028 #x10
  # Buffer for torque delay
delay_OCP_ms: 1    # in ms
delay_sim_cycle: 2 # in HF cycles
  # Proportional-integral torque control gains
Kp_low: [.2, .2, .2, .2, .2, .2, .2  ]
Ki_low: [.001, .001, .001, .001, .001, .001, .01]
Kd_low: [.00001, .00001, .00001, .00001, .00001, .00001, .00001]
u_avg_filter_length: 1 #8 # in HF cycles
x_avg_filter_length: 20  #20 #8 # in HF cycles