# ROBOT : 'talos_arm' 
# TASK  : circle trajectory tracking
# with Low-Pass-Filter (LPF) in dynamics



# General 
LPF_TYPE: 1
f_c: 5                                                        # Low-pass filter cut-off frequency
tau_plus_integration: False
dt: 0.01                                                      # OCP integration step 
N_h: 400                                                      # Horizon length in nodes
maxiter: 100                                                  # Max number of iterations in DDP
q0: [ 1.4399,  0. , -1.1781,  0. ,  0. ,  0., -0.5236]        # (qmax + qmin) /2
dq0: [0.,0.,0.,0.,0.,0.,0.]                                   # Initial robot joint velocity


# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'translation', 'velocity',
WHICH_COSTS: ['translation', 'stateReg', 'ctrlRegGrav', 'stateLim']  

# Cost function weights and activations
 # 'stateReg' : state regularization  
stateRegWeights: [0., 0., 0., 0., 0., 0., 0., 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: 0.01
stateRegWeightTerminal: 0.01
stateRegRef: 'DEFAULT'  # 'DEFAULT' = [q0, v0]

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.001
ctrlRegWeightTerminal: 0.1
ctrlRegRef: 'DEFAULT'   # DEFAULT = g(q) | NOT used for 'ctrlRegGrav' cost


# 'wReg' : unfiltered torque regularization
wRegWeight: 0.00001
wRegRef: 'tau0'  # in ['zero', 'tau0', 'gravity']

# 'wLim' : unfiltered torque limit
wLimWeight: 10.


 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 10.
frameTranslationWeightTerminal: 10.
frameTranslationRef: 'DEFAULT' 
frameTranslationFrameName: 'gripper_left_joint'
frameCircleTrajectoryRadius: 0.1       # in m
frameCircleTrajectoryVelocity: 1.5     # in rad/s
CIRCLE_LOCAL_PLANE: 'XZ'               # LOCAL plane in which the circle lies

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
frameVelocityWeight: .1
frameVelocityWeightTerminal: .1
frameVelocityRef: 'DEFAULT'      
frameVelocityFrameName: 'gripper_left_joint'  

 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 100.
stateLimWeightTerminal: 100.
coef_xlim: 1.

 # 'ctrlLim' : torque limits
# ctrlLimWeights: [1., 1., 1., 1., 1., 1., 1.]
# ctrlLimWeight: 0.
# ctrlLimWeightTerminal: 0.
# coef_ulim: 1.

# armature
armature: [.1, .1, .1, .1, .1, .1, .0]